#!/usr/bin/perl

use warnings;
use strict;
use v5.36.0;

use Data::Dumper;

use JSON;

use lib "./";
use lib "./plugins";

use Common::CS_Config;

use PhoneTree::BackupRestore;
use PhoneTree::Members;
use PhoneTree::Messages;

use File::Copy;
use Proc::Simple;
use Mojo::IOLoop;
use Mojolicious::Lite;

my $messenger;
my $backupPassphrase = 'ReesesPieces';

#main:
{
	##
	##  On startup, schedule test every minute to see if Messenger
	##  task needs to be started. (This is for
	##  instances where a shutdown happened while
	##  messages were being sent.)
	##
	Mojo::IOLoop->recurring( 60 => sub($bob)
		{
			if ( messagesArePending())
			{
				##
				##  Is a messenger running?
				##
				if (( defined( $messenger) && ! $messenger->poll()) ||
					( !defined( $messenger)))
				{
					startMessenger();
				}
			}
		});

	#------------------------------------------------------------------------------
	#  get '/login' -- This is the main login screen
	#------------------------------------------------------------------------------
	get '/login' => sub
	{
		my $self = shift( @_);

		$self->render( 'login');
	};

	#------------------------------------------------------------------------------
	#  post '/login' -- This screen processes the login entry
	#------------------------------------------------------------------------------
	post '/login' => sub
	{
		my $self = shift;
		my $username = $self->param( 'user');
		my $password = $self->param( 'password');

		if ( isPhoneTreeAdmin( $username, $password))
		{
			my $cookie = Mojo::Cookie::Response->new( name=>'UID', value=> getPhoneTreeAdminUID(), expires=>time() + 3600);
			$self->res->cookies( $cookie);
			my $lastCall = $self->session->{lastCall};
			$lastCall =~ s/^\/phonetree//;
			if ( defined( $lastCall) and length( $lastCall))
			{
				print "Redirecting to $lastCall\n";
				$self->redirect_to( $lastCall);
			}
			else
			{
				print "Rendering \/\n";
				$self->redirect_to( '/');
			}
		}
		else
		{
			$self->flash( error=> 'Invalid login name or password!');
			$self->redirect_to( '/login');
		}
	};

	get '/logoff' => sub
	{
		my $self = shift;
		my $cookie = Mojo::Cookie::Response->new( name=>'UID', value=> '', expires=>1);
		$self->res->cookies( $cookie);

		$self->redirect_to( '/login');
	};



	#------------------------------------------------------------------------------
	#  EVERY page below here first gets autothenticated by this routine
	#------------------------------------------------------------------------------
	under sub
	{
		my $self = shift;

		##
		##	Is the user already logged in as an admin?
		##
		if ( defined( $self->cookie( 'UID')) && ( isPhoneTreeAdminUID( $self->cookie('UID'))))
		{
			return 1;
		}

		##
		##  Remember the page asked for
		##
		$self->session->{lastCall} = $self->{tx}->{req}->{url}->{path}->{path};
		$self->redirect_to( 'login');

		return;
	};


	#------------------------------------------------------------------------------
	#	get '/'
	#------------------------------------------------------------------------------
	get '/' => sub
	{
		my ($self) = @_;
	

		$self->render( 'index');
	};


	#------------------------------------------------------------------------------
	#  get '/index' 
	#------------------------------------------------------------------------------
	get '/index' => sub
	{
		my ($self) = @_;

		$self->redirect_to( '/');
	};


	#------------------------------------------------------------------------------
	#  get '/config' 
	#------------------------------------------------------------------------------
	get '/config' => sub
	{
		my ($self) = @_;

		my %configInfo = getConfigInfo();
		$self->stash( %configInfo);
		$self->render('editConfig');
	};

	#------------------------------------------------------------------------------
	#	post '/saveConfig'
	#		This call saves the newly defined configuration settings
	#------------------------------------------------------------------------------
	post '/saveConfig' => sub
	{
		my $self = shift(@_);

		if ( $self->param('submit') =~ /Save/)
		{
			my %config;

			$config{"EmailServer"} = $self->param( "EmailServer");
			$config{"EmailPort"} = $self->param( "EmailPort");
			$config{"EmailUID"} = $self->param( "EmailUID");
			$config{"EmailPWD"} = $self->param( "EmailPWD");
			$config{"PhoneTreeEmailSender"} = $self->param( "PhoneTreeEmailSender");
			$config{"TwilioAcct"} = $self->param( "TwilioAcct");
			$config{"TwilioAuth"} = $self->param( "TwilioAuth");
			$config{"TwilioPhone"} = $self->param( "TwilioPhone");
			$config{"TwilioIntro"} = $self->param( "TwilioIntro");
			$config{"TwilioGender"} = $self->param( "TwilioGender");
			$config{"Logging"} = ($self->param( "Logging") eq 'Y') ? 1 : 0;
			$config{"MaxRetries"} = $self->param( "MaxRetries");
			$config{"DelayBetweenRetries"} = $self->param( "DelayBetweenRetries");
			$config{"CallerIDNumber"} = $self->param( "CallerIDNumber");
			$config{"PhoneTreeAdminLogin"} = $self->param( "PhoneTreeAdminLogin");
			$config{"PhoneTreeAdminPWD"} = $self->param( "PhoneTreeAdminPWD");

			saveConfig( %config);
		}

		$self->stash( restored => "no", textMessage=>'', title=>'');
		$self->render( "index");
	};

	#------------------------------------------------------------------------------
	#	get '/cleanBackup'
	#		Removes the backup file created for file download and redirects to /index
	#------------------------------------------------------------------------------
	get '/cleanBackup' => sub
	{
		my ($self) = @_;
		print "Removing public/$PhoneTree::BackupRestore::baseBackupFilename\n";
		unlink( "public/$PhoneTree::BackupRestore::baseBackupFilename");
		$self->render( "index");
	};

	#------------------------------------------------------------------------------
	#	get '/editMembers'
	#------------------------------------------------------------------------------
	get '/editMembers' => sub
	{
		my ($self) = @_;

		$self->render( 'editMembers');
	};
	
	#------------------------------------------------------------------------------
	#	get '/editGroups'
	#------------------------------------------------------------------------------
	get '/editGroups' => sub
	{
		my ($self) = @_;

		$self->render( 'editGroups');
	};

	#------------------------------------------------------------------------------
	#	get '/sendMessage'
	#------------------------------------------------------------------------------
	get '/sendMessage' => sub
	{
		my ($self) = @_;

		$self->render( 'sendMessage');
	};
	
	#------------------------------------------------------------------------------
	#	get '/scheduled'
	#------------------------------------------------------------------------------
	get '/scheduled' => sub
	{
		my ($self) = @_;

		$self->render( 'sendScheduledMessage');
	};

	#------------------------------------------------------------------------------
	#	get 'viewScheduled'
	#------------------------------------------------------------------------------
	get 'viewScheduled' => sub
	{
		my ( $self) = @_;

		$self->render( 'viewScheduledMessages');
	};
	
	#------------------------------------------------------------------------------
	#	get '/restore'
	#		This call routes to the page for restoring from a backup
	#------------------------------------------------------------------------------
	get '/restore' => sub
	{
		my $self = shift;

		$self->stash( backupFile => undef);
		$self->render( 'restoreBackup');
	};



	#------------------------------------------------------------------------------
	#	post '/addMember' 
	#------------------------------------------------------------------------------
	post '/addMember' => sub
	{
		my ( $self) = @_;

		my $firstName =  $self->param( 'firstname');
		my $lastName =  $self->param( 'lastname');
		my $homephone = $self->param( 'landline');
		my $cellphone = $self->param( 'cellphone');
		my $email = $self->param( 'email');
		my $tryFirst = $self->param( 'tryFirst');
		my $trySecond = $self->param( 'trySecond');
		my $tryThird = $self->param( 'tryThird');
		my $callAll = ( $self->param('SendMsgs') eq 'toAll') ? 1 : 0;
		my $rowid = 'new';
		

		writeContactInfo( {
							firstname => $firstName,
							lastname =>  $lastName,
							homephone => $homephone,
							cell => $cellphone,
							email => $email,
							tryFirst => $tryFirst,
							trySecond => $trySecond,
							tryThird => $tryThird,
							callAll => $callAll,
							rowid => $rowid
						  }
						 );


		$self->render( json => { saved => 1, name => "$firstName $lastName"} );
	};

	#------------------------------------------------------------------------------
	#	post '/updateMember' 
	#------------------------------------------------------------------------------
	post '/updateMember' => sub
	{
		my ( $self) = @_;

		my $firstName =  $self->param( 'firstname');
		my $lastName =  $self->param( 'lastname');
		my $homephone = $self->param( 'landline');
		my $cellphone = $self->param( 'cellphone');
		my $email = $self->param( 'email');
		my $tryFirst = $self->param( 'tryFirst');
		my $trySecond = $self->param( 'trySecond');
		my $tryThird = $self->param( 'tryThird');
		my $callAll = ( $self->param('SendMsgs') eq 'toAll') ? 1 : 0;
		my $rowid = $self->param( 'rowid');
		

		writeContactInfo( {
							firstname => $firstName,
							lastname =>  $lastName,
							homephone => $homephone,
							cell => $cellphone,
							email => $email,
							tryFirst => $tryFirst,
							trySecond => $trySecond,
							tryThird => $tryThird,
							callAll => $callAll,
							rowid => $rowid
						  }
						 );


		$self->render( json => { saved => 1, name => "$firstName $lastName"} );
	};

	#------------------------------------------------------------------------------
	#	post '/removeMember' 
	#------------------------------------------------------------------------------
	post '/removeMember' => sub
	{
		my $self = shift( @_);

		my $json = $self->req->json();

		my $rowid = $json->{rowid};
		
		print "\nAsked to delete row $rowid\n";

		my $deleted = deleteMember( $rowid);

		$self->render( json => { saved => $deleted});
	};

	#------------------------------------------------------------------------------
	#	post '/saveGroup' 
	#		This post expects to receive group member information in the following 
	#		JSON format:
	#			{  group: groupName, members:[ name1, name2,...]}
	#		It then proceeds to update the Groups table so that the provided
	#		members are the members of the named group.
	#------------------------------------------------------------------------------
	post '/saveGroup' => sub
	{
		my $self = shift( @_);

		my $json = $self->req->json();

		my $groupName = $json->{group};
		my $members = $json->{members};
		
		print "\nAsked to add a new group named $groupName consisting of the follwing members:\n\t". join( "\n\t", @{$members}) . "\n\n";

		my $added = saveGroup( $groupName, $members);

		$self->render( json => { saved => $added});
	};

	#------------------------------------------------------------------------------
	#	post '/removeGroup' 
	#		This post expects to receive group member information in the following 
	#		JSON format:
	#			{  group: groupName}
	#		It then removes the named group from the Groups table.
	#------------------------------------------------------------------------------
	post '/removeGroup' => sub
	{
		my $self = shift( @_);

		my $json = $self->req->json();

		my $groupName = $json->{group};
		
		print "\nAsked to remove the roup named $groupName\n";

		my $added = removeGroup( $groupName);

		$self->render( json => { deleted => $added});
	};

	#------------------------------------------------------------------------------
	#	post '/sendMessage' 
	#------------------------------------------------------------------------------
	post '/sendMessage' => sub
	{
		my ( $self) = @_;

		my $toList = $self->every_param( 'individuals');
		my $from =  $self->param( 'from');
		my $message = $self->param( 'theMessage');
		my $subject = $self->param( 'subject');
		my $whenToSend = $self->param( 'whenToSend');
		my $messageIds = $self->param( 'messageIds');   #  Ids of messages to replace, may be undefined.

		##
		##  Is this a change to a scheduled message?
		##
		if ( defined( $messageIds))
		{
			print "\n\nMessage IDS are: $messageIds\n\n";
			openDB();
			startTransaction();

			my @messagesToRemove = split( ',', $messageIds);
			deleteSelectedMessages( \@messagesToRemove);
		}

		##
		##  Queue up the list of messages to send
		##
		foreach my $id (@$toList)
		{
			my $info = readContactInfo( $id);
			my $name = $info->{firstname} . ' ' . $info->{lastname};
			print "Sending message to $name ($id) from $from with a subject of \"$subject\" and a message of \"$message\".\n";
			storeMessage( $id, $from, $subject, $message, $whenToSend);
		}

		##
		##  Commit transaction, if rescheduling messages
		##
		if ( defined( $messageIds))
		{
			commitTransaction();
			closeDB();
		}
		

		##
		##  Make sure the messenger is sending queued messages
		##
		startMessenger();

		if ( defined( $whenToSend))
		{
			$self->stash( title => 'Messages Queued', textMessage=>"Messages will be sent on $whenToSend", showFor => 2000);
		}
		else
		{
			$self->stash( title => 'Messages Sending', textMessage=>"Messages are being sent", showFor => 2000);
		}

		$self->render( "index");
	};
	
	
	#------------------------------------------------------------------------------
	#	post '/restore'
	#		This call carries out the actual restore
	#------------------------------------------------------------------------------
	post '/restore' => sub
	{
		my $self = shift;
	 
		# Check file size
		if ($self->req->is_limit_exceeded)
		{
			return $self->render(text => 'File is too big.', status => 200);
		}
	 
		# Process uploaded file
		my $filename = $self->param('filename');

		my %response = restoreBackup( $filename, $backupPassphrase);

		$self->stash( textMessage => $response{textMessage}, backupFile=> $response{backupFile}, title=> $response{title}, showFor => $response{showFor});
		
		if ( !defined( $response{backupFile}))
		{
			print "Rendering index...\n";
			$self->render( 'index');
		}
		else
		{
			$self->render( 'restoreBackup');
		}
	};
	
	#------------------------------------------------------------------------------
	#  post '/restoreCommon'
	#  		This call restores the common config settings from the provided
	#  		temporary backup filename.
	#------------------------------------------------------------------------------
	post '/restoreCommon' => sub
	{
		my $self = shift;

		my $json = $self->req->json();
		my $backupName = $json->{backupName};
		
		restoreCommonSettings( $backupName, $backupPassphrase);
		$self->render( 'index');
	};
	
	#------------------------------------------------------------------------------
	#  post '/releaseBackupData'
	#  		This call releases the temporarily stored common configuration settings
	#  		backup file created during the restore.
	#------------------------------------------------------------------------------
	post '/releaseBackupData' => sub
	{
		my $self = shift;

		my $json = $self->req->json();
		my $backupName = $json->{backupName};
		
		releaseBackupData( $backupName);
		$self->render( 'admin');
	};
	

	#------------------------------------------------------------------------------
	#	get '/editQueuedMessages'
	#		This call allows the user to edit the queued messages whose rowids
	#		are passed in the "messageIds" parameter.
	#------------------------------------------------------------------------------
	get '/editQueuedMessages' => sub
	{
		my $self = shift;

		my $messageIds = $self->param( 'messageids');
		my @idList = split( ',', $messageIds);

		##
		##  Get the message content of the first message in the list
		##
		my $message = getQueuedMessage( $idList[0]);
		print "The message is:\n" . $message->{message} ."\n";
		my @recipients = getMessageRecipients( \@idList);
		$self->stash(
			 			message => $message, 
						recipients =>  \@recipients,
						messageIds => $messageIds
					);

		$self->render( '/rescheduleMessage');
	};


	#------------------------------------------------------------------------------
	#	post '/deleteQueuedMessages'
	#		This call frees the queued messages whose rowids are passed in the
	#		"messageIds" parameter.
	#------------------------------------------------------------------------------
	post '/deleteQueuedMessages' => sub
	{
		my $self = shift;

		my $json = $self->req->json();
		my $idList = $json->{messageIds};

		if ( deleteSelectedMessages( $idList))
		{
			$self->render( status => 201, text => 'Complete');
		}
		else
		{
			$self->render( status=>409, text=>'An SQL error occurred.');
		}
	};

	#------------------------------------------------------------------------------
	#	websocket '/getContacts'
	#		This method is called to get a list of all contacts.  It returns a hash
	#		where the keys are the contact ID.
	#------------------------------------------------------------------------------
	websocket '/getContacts' => sub
	{
		my $self = shift;

		my $list = readContacts();
		$self->send( {json => $list}, sub { my ($ws, $err) = @_; print "Send failed: $err\n" if $err});

##-->		$self->on( drain => sub { print "All data sent successfully!\n"});
##-->		$self->on( finish => sub { my ($ws, $code, $reason) = @_; print "Closed with code ($code)!  $reason\n";});
	};

	#------------------------------------------------------------------------------
	#	websocket '/getContactInfo'
	#		This method is called to get the information about a specific contact,
	#		identified by the ID.
	#------------------------------------------------------------------------------
	websocket '/getContactInfo' => sub
	{
		my $self = shift;

		##
		##  See if we got a message
		##
		$self->on( json => sub
					{
						my ($self, $rowid) = @_;
						
						my $info = readContactInfo( $rowid);

##-->						print "Sending:\n" . Dumper( $info) . "\n\n";
						##
						##  Send back the response
						##
						$self->send( {json => $info});
					}
				  );
	};

	#------------------------------------------------------------------------------
	#	websocket '/getGroups'
	#		This method is called to get a list of all contacts.  It returns an
	#		array where each row contains a group name.
	#------------------------------------------------------------------------------
	websocket '/getGroups' => sub
	{
		my $self = shift;
		my $list = readGroups();
		$self->send( {json => $list});
	};

	#------------------------------------------------------------------------------
	#	websocket '/getGroupMembers'
	#		This method is called to get the member list of a specific group name.
	#		It returns an array where each row contains the following JSON
	#			{ members: <memberName>, isGroup: [0|1]}
	#------------------------------------------------------------------------------
	websocket '/getGroupMembers' => sub
	{
		my $self = shift;

		##
		##  See if we got a message
		##
		$self->on( message => sub
					{
						my ($self, $group) = @_;
						
						print "I see group $group\n";
						my $info = getGroupMembers( $group);

##-->						print "Sending:\n" . Dumper( $info) . "\n\n";
						##
						##  Send back the response
						##
						$self->send( {json => $info});
					}
				  );
	};

	#------------------------------------------------------------------------------
	#	websocket '/getMessageList'
	#		This method is called to get a list of members that are in the message
	#		queue.  It may optionally receive a type of 'all' to list all members.
	#		If the type is unspecified or not 'all', it defaults to a list of 
	#		all messages that have not yet been sent.  It returns a reference
	#		to an array of hashrefs.  The hashrefs reference the fields:
	#			(rowid, fromWho, subject, message, sendOn, status, retry)
	#------------------------------------------------------------------------------
	websocket '/getMessageList' => sub
	{
		my $self = shift;

		##
		##  Get a list of pending members
		##
		$self->on( message => sub
					{
						my ($self, $type) = @_;

						my $list = ( defined($type) && ($type eq 'all')) ? allMessages() : allPendingMessages();
						$self->send( {json => $list});
					}
				 );
	};

	#------------------------------------------------------------------------------
	#	websocket '/messagesVary'
	#		This call checks to see if the messages queued to be sent, that are
	#		identified by their rowids in the comma-separated list of numbers,
	#		have varying message content.  A non-zero value is returned if the
	#		message texts differ.
	#------------------------------------------------------------------------------
	websocket '/messagesVary' => sub
	{
		my $self = shift;

		##
		##  Get a list of pending members
		##
		$self->on( message => sub
					{
						my ($self, $list) = @_;

						my @rowIds = split( ",", $list);
						my $result = messagesVary( \@rowIds);
						$self->send( {json => $result });
					}
				 );
	};
	
	#------------------------------------------------------------------------------
	#	websocket '/backup'
	#		This call stores the existing config and database in a tar file,
	#		encrypts it, and then makes it available for download.
	#------------------------------------------------------------------------------
	websocket '/backup' => sub
	{
		my $ws = shift;

		$ws->on (text => sub
			{
				$ws->inactivity_timeout(300);
				my ($ws, $message) = @_;

				print "Got a '$message' request\n";
				if ( $message =~ m/Backup/)
				{
					my $backupFilename = backupData( $backupPassphrase);
					$ws->send( $backupFilename);
				}
				else
				{
					$ws->send( "What??!");
				}
			}
			);
	};



	app->config( hypnotoad=>{listen =>['http://*:3000']});
	app->secrets( ['Your mileage may vary']);
	return app->start;
}

#------------------------------------------------------------------------------
#  sub startMessenger()
#  		This routine launches the messenger app to send any messages which are
#  		queued up, unless it is already running.
#------------------------------------------------------------------------------
sub startMessenger()
{
	return;
	print "*****************************\n";
	print "  Starting the messenger...\n";
	print "*****************************\n";
	$messenger //= Proc::Simple->new();

	if ( ! $messenger->poll())
	{
		$messenger->start( "perl messenger");
	}
}

#------------------------------------------------------------------------------
#  sub isPhoneTreeAdmin(user, $pwd)
#  		Returns true if the name and password match the configured value for
#  		the PhoneTree admin.
#------------------------------------------------------------------------------
sub isPhoneTreeAdmin( $user, $pwd)
{
	my %config = getConfigInfo();

	return( ($user eq $config{PhoneTreeAdminLogin}) && ( $pwd eq $config{PhoneTreeAdminPWD}));
}

#------------------------------------------------------------------------------
#	sub getPhoneTreeAdminUID()
#		This routine generates a random 10 character alpha-numeric string
#		suitable for an Admin.
#------------------------------------------------------------------------------
sub getPhoneTreeAdminUID()
{
	my @chars = ( 'a'..'z', '0'..'9', 'A'..'Z');
	my $id;
	do 
	{
		$id = '';
		for( 1..10)
		{
			$id .= $chars[ int rand( @chars)];
		}
	} while( (unpack( "%32W*", $id) % 42) != 0);

	return $id;
}

#------------------------------------------------------------------------------
#	sub isPhoneTreeAdminUID( $id) 
#------------------------------------------------------------------------------
sub isPhoneTreeAdminUID( $id)
{
	return( !( unpack( "%32W*", $id) % 42));
}

